services:
  nut:
    image: image: ghcr.io/npetersendk/nut-alpine:latest
    container_name: Nut-Server
    privileged: true
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    ports:
      - 3493:3493
    devices:
      - /dev/bus/usb:/dev/bus/usb:rw
    volumes:
      - ./config/nut:/etc/nut:rw
    restart: always