services:
  nut:
    image: niko/nut:v0.1
    container_name: Nut-Server
    privileged: true
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    ports:
      - 3493:3493
    devices:
      - /dev/bus/usb:/dev/bus/usb:rw
    volumes:
      - ./config/nut:/etc/nut:rw
    restart: always