#!/bin/sh
set -e

# Create required directories with correct permissions
mkdir -p /var/run/nut /run
chown -R nut:nut /var/run/nut /run /etc/nut 
chmod 750 /var/run/nut /run /etc/nut
chmod 640 /etc/nut/* 
chmod 755 /etc/nut/notifycmd.sh

# Fix USB permissions
if [ -d "/dev/bus/usb" ]; then
    chgrp -R nut /dev/bus/usb
    chmod -R g+rw /dev/bus/usb
fi

NOTIFYTYPE=DOCKERONLINE sh /etc/nut/notifycmd.sh

# Start the UPS driver
/usr/sbin/upsdrvctl start

# Start the UPS daemon
/usr/sbin/upsd

# Start upsmon in foreground mode
exec /usr/sbin/upsmon -D